version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
        - "5672:5672"
  publisher:
    build: PointToPointMessagingWithRabbitMQ/Consumer/.
  consumer:
    build: PointToPointMessagingWithRabbitMQ/Publihser/.
    ports:
        - "5000:5000"
        - "5001:5001"
